# Generated by Django 4.2.7 on 2023-11-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='Nombre',
            field=models.CharField(max_length=255),
        ),
    ]
