# Generated by Django 4.2.7 on 2023-11-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contacto_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Correo',
            new_name='Email',
        ),
    ]
