# Generated by Django 4.2.7 on 2023-11-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_rename_correo_contacto_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='Email',
            new_name='Correo',
        ),
    ]
