# Generated by Django 4.2.7 on 2023-11-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedias',
            name='Imagen',
            field=models.ImageField(upload_to='static/social/images'),
        ),
    ]
