# Generated by Django 4.2.7 on 2023-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_socialmedias_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedias',
            name='Imagen',
            field=models.ImageField(upload_to='social/images'),
        ),
    ]
