# Generated by Django 4.2.7 on 2023-11-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_socialmedias_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='socialMedias',
        ),
    ]
